#HOME_ROUTE="/meajuda"
HOME_ROUTE="/"
SOBRE_ROUTE="/ajuda-categorias/sobre-nohs"
CONTA_ROUTE="/ajuda-categorias/conta"
CARTAO_ROUTE="/ajuda-categorias/cartao-noh"
BOLETOS_ROUTE="/ajuda-categorias/boletos"
PIX_ROUTE="/ajuda-categorias/pix"
MENSALIDADE_ROUTE="/ajuda-categorias/mensalidade"